### PR TITLE
Redesign `Session` to represent one request-response session.

### PR DESCRIPTION
**Pull request by c0per**
`Session` and `CookieStore` are redesigned as discussed in issue #19 

Other stores are not changed. Session interfaces changes a bit.

### CODE REVIEW

**Comment by c0per** [comment]
I updated README and test, which might be helpful.

**Comment by jcs224** [comment]
After going through this change and running it through it's paces, I think this is great improvement! The new model seems to solve some small bugs I've been having in my own app because of data sometimes overlapping between requests. I'm going to write a small migration guide (because it's a breaking change), then I'll merge and bump the major version up.

Thanks!

**Comment by c0per** [comment]
> After going through this change and running it through it's paces, I think this is great improvement! The new model seems to solve some small bugs I've been having in my own app because of data sometimes overlapping between requests. I'm going to write a small migration guide (because it's a breaking change), then I'll merge and bump the major version up.
> 
> Thanks!

Thank you for that. Before merging, have you checked out another verion of the `initMiddleware()` api in the discussion #22 (some later comments). I actually think that solves what you said about session in different sub routes and support different config / store per routes.

**Comment by c0per** [comment]
⬆️，by which I mean this: https://github.com/jcs224/oak_sessions/discussions/22#discussioncomment-3186043

**Comment by jcs224** [comment]
I'll hold off until we resolve which way to go in #22 .

**Pull request merged**
