### PR TITLE
Make flash survive redirects

### PR DESCRIPTION
**Pull request by aslakhellesoy**
Hi - thanks for this library.

I assume the intent with the flash is to survive redirects. For example a POST handler sets an error message, redirects to another page, and the GET to that page reads the flash.

I have fixed this by not clearing the flash before a new request is handled. Instead, individual flash messages are only cleared once they are accessed. (This way flash messages can survive for several requests).

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
FWIW, this is also how it works in [remix](https://remix.run/docs/en/v1/api/remix#sessionflashkey-value)

**Comment by jcs224** [comment]
Thanks for your interest in this library! This is my first sessions library built out of self-need, so I'm sure there are lots of things that could be improved.

I would be grateful if you also provided the doc update, thanks!

**Comment by jcs224** [comment]
Wow, thanks @aslakhellesoy! There's a lot of good stuff here. Tested the changes locally and with my own app, there are some little fixes I'll make then I'll tag a new release.

In the future, when there are multiple separate issues, I would prefer them to be in separate PRs, for example, one PR for flash messages, a different one for dependency updates, etc.

Great job!

**Comment by aslakhellesoy** [comment]
Awesome thanks!

**Pull request merged**
