### PR TITLE
CI Improvements

### PR DESCRIPTION
**Pull request by akatechis**
- [x] Make CI workflow run on pull requests
- [x] Add linting and type-checking to CI workflow.
- [x] Fix various lint issues that arise from linting the code.

### CODE REVIEW

**Comment by akatechis** [comment]
Excessive diffs in `makeStore.ts` file is because I ran the formatter on the file after making a bunch of changes, and it seems like it changed the quotes.

**Comment by akatechis** [comment]
@jcs224 Not sure what to do with this...

The postgres test job is failing, because of an error that I just don't know how to resolve:

```
error: Uncaught (in promise) PostgresError: type "string" does not exist
    const error = Errors.postgres(parseError(x))
                         ^
    at ErrorResponse (https://deno.land/x/postgresjs@v3.2.4/src/connection.js:765:26)
    at handle (https://deno.land/x/postgresjs@v3.2.4/src/connection.js:472:6)
    at data (https://deno.land/x/postgresjs@v3.2.4/src/connection.js:316:9)
    at https://deno.land/x/postgresjs@v3.2.4/polyfills.js:148:32
```

I suspect it has to do with the generic type param that the `postgres` constructor function takes, but I don't know what it's expecting, because based on the docs for postgresjs library, there's no mention of it in the docs. I did some sleuthing through their source code, and it seems it's used for (de)serializing postgres types <-> JS/TS types, but it's weird that something as basic as "string" would need to be passed in...?

Thoughts on what to do with it?

**Comment by jcs224** [comment]
Excellent work on this, @akatechis!

I believe I've isolated the Postgres issue... The error isn't a typescript error, it's a postgres error. I'm actually using CockroachDB in my own stuff, not true Postgres, and they have very similar but not identical APIs.

This particular error is the `string` type in Cockroach isn't compatible with the `varchar` type native to Postgres. In `src/stores/PostgresStore.ts`, change line 14 to this:
```ts
await this.sql`create table if not exists ${this.sql(this.tableName)} (id varchar(21) not null primary key, data varchar)`;
```

**Comment by akatechis** [comment]
Phew, I think it's ready @jcs224

**Comment by jcs224** [comment]
Incredible, thank you!

**Pull request merged**
